name: CI/CD for Flask App

on:
  push:
    branches: [main]
  pull_request:

env:
  FLASK_ENV: development  # giống GitLab CI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  deploy:
    needs: test  # chỉ chạy sau khi test xong
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # giống `only: main` trong GitLab

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Simulate deployment
        run: |
          python app.py &
          sleep 5
          curl http://localhost:5000
