name: Python Test CI

on: [push, pull_request]  # chạy khi có push hoặc pull request

jobs:
  test:
    runs-on: ubuntu-latest

    container: python:3.10  # giống image trong GitLab CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
